### ISSUE TITLE
What's the best way to add phone and email claims?

### ISSUE THREAD

**Issue by xyting** [IdentityServer/IdentityServer4.AspNetIdentity#10]
The currently impls of `IProfileService` use `IUserClaimsPrincipalFactory` to get the claims about the identity user, but the default impls of IUserClaimsPrincipalFactory not include the phone and email. So if I need to add phone and email claims, I need to change

```csharp
  public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);
            var principal = await _claimsFactory.CreateAsync(user);
            context.AddFilteredClaims(principal.Claims);
        }
```

to 

```csharp
public async Task GetProfileDataAsync(ProfileDataRequestContext context) {
            var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);
            var principal = await _claimsFactory.CreateAsync(user);

            var claims = new List<Claim>(principal.Claims);
            
            // Add phone & email
            if (_userManager.SupportsUserEmail) {
                var email = await _userManager.GetEmailAsync(user);
                if (!string.IsNullOrWhiteSpace(email)) {
                    claims.AddRange(new[]
                    {
                        new Claim(JwtClaimTypes.Email, email),
                        new Claim(JwtClaimTypes.EmailVerified,
                            await _userManager.IsEmailConfirmedAsync(user) ? "true" : "false", ClaimValueTypes.Boolean)
                    });
                }
            }

            if (_userManager.SupportsUserPhoneNumber) {
                var phoneNumber = await _userManager.GetPhoneNumberAsync(user);
                if (!string.IsNullOrWhiteSpace(phoneNumber)) {
                    claims.AddRange(new[]
                    {
                        new Claim(JwtClaimTypes.PhoneNumber, phoneNumber),
                        new Claim(JwtClaimTypes.PhoneNumberVerified,
                            await _userManager.IsPhoneNumberConfirmedAsync(user) ? "true" : "false", ClaimValueTypes.Boolean)
                    });
                }
            }

            context.AddFilteredClaims(claims);
        }
```

@brockallen what is the best way to do that?

**Comment by brockallen** [comment]
Oh right, maybe they should. I'll look into it.

**Comment by brockallen** [comment]
I thought about this and I'd argue that this should be in the IUserClaimsPrincipalFactory. I don't want to provide a custom IUserClaimsPrincipalFactory  and this is, by the AspId design, where you do your claims mapping. The ProfileService's job in this context is really to map from the AspId framework to the IdSvr framework.

**Comment by brockallen** [comment]
Ok, I thought some more and I guess I'll do a UserClaimsPrincipalFactory -- it'll be registered on the ASP.NET Identity IdentityBuilder... more info soon.

**Comment by brockallen** [comment]
Ok, added: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/rc2/src/IdentityServer4.AspNetIdentity/UserClaimsFactory.cs

Feedback welcome.

**Comment by xyting** [comment]
Yes, I also agree that this should be in the IUserClaimsPrincipalFactory, maybe the best way is this repo use the default impls of IUserClaimsPrincipalFactory provided by ASP.NET Identity, and depend on the end user to provide the custom impls of IUserClaimsPrincipalFactory.

**Comment by xyting** [comment]
@brockallen Your impls of IUserClaimsPrincipalFactory and Identity impls have different DI lifetime,

see [Your DI](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/rc2/src/IdentityServer4.AspNetIdentity/IdentityBuilderExtensions.cs#L20)

see [Identity repo DI](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IdentityServiceCollectionExtensions.cs#L65)

why ?

**Comment by brockallen** [comment]
Hmm, not sure why they choose scoped. I guess because they assume there's a DbContext at the end... but that's silly. Anyway, I emailed them to ask.
