### ISSUE TITLE
Use builder.AddProfileService() extension method

### ISSUE THREAD

**Issue by xyting** [IdentityServer/IdentityServer4.AspNetIdentity#11]
See [IdentityServerBuilderExtensions](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/IdentityServerBuilderExtensions.cs#L38-L39),

```csharp
 builder.AddResourceOwnerValidator<ResourceOwnerPasswordValidator<TUser>>();
 builder.Services.AddTransient<IProfileService, ProfileService<TUser>>();
```

why not

```csharp
 builder.AddResourceOwnerValidator<ResourceOwnerPasswordValidator<TUser>>();
 builder.AddProfileService<ProfileService<TUser>>();
```

Use `builder.AddProfileService()` is benefit from the lifetime of `IProfileService` is control by `IdentityServer4`, and always is consistent.

**Comment by brockallen** [comment]
Good point -- I'll add it to core.

**Comment by brockallen** [comment]
Seems this was done a while ago. Closing.
