### ISSUE TITLE
Make ProfileService and validator methods virtual.

### ISSUE THREAD

**Issue by HeathJared** [IdentityServer/IdentityServer4.AspNetIdentity#12]
I have additional properties that are required for user account management (like various enabled flags) and would like to be able to extend the base functionality.

**Comment by brockallen** [comment]
Ok, good idea.

**Comment by brockallen** [comment]
Done

**Comment by maganuk** [comment]
Hey brock, 

Is this the correct way to override the ProfileService:

    public class ExtendedProfileServe : ProfileService<User>
    {

        private readonly UserManager<User> _userManager;

        public ExtendedProfileServe(UserManager<User> userManager, IUserClaimsPrincipalFactory<User> claimsFactory) : base(userManager, claimsFactory)
        {
            _userManager = userManager;
        }

        public override async Task IsActiveAsync(IsActiveContext context)
        {
            var locked = true;

            var sub = context.Subject.FindFirst("sub")?.Value;

            if (sub != null)
            {
                var user = await _userManager.FindByIdAsync(sub);

                if (user != null)
                    locked = await _userManager.IsLockedOutAsync(user);
            }

            context.IsActive = !locked;
        }
    }

and then doing: 

    services.AddTransient<IProfileService, ExtendedProfileServe>();


Thanks
