### ISSUE TITLE
UserNameClaimType and JwtClaimTypes.Name. Should they really be mapped?

### ISSUE THREAD

**Issue by domrin123** [IdentityServer/IdentityServer4.AspNetIdentity#13]
Hi,

In https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/IdentityServerBuilderExtensions.cs 

we have 

` options.ClaimsIdentity.UserNameClaimType = JwtClaimTypes.Name;`

It's my understanding that the UserNameClaimType is referring to the "username" of the user and not the OpenID Connect "name" claim. The result at the moment is that when the id token is returned, we're getting the username in the "name" claim which should actually be the full name.

In IdentityServer3 I believe the UserName was mapped to the PreferredUserName which makes more sense.

Cheers,

Dom

**Comment by brockallen** [comment]
Sure, but ASP.NET Identity is broken in this regard. They think the username should be the display name, which is dumb.

**Comment by domrin123** [comment]
Woah what. So they think that the "UserName" that we see in the db should contain the full name of the user? I'm confused now 😕

**Comment by brockallen** [comment]
No, they don't have the notion of the user's "name" -- only the username, which is the text a user types into a login field and that in many scenarios is unrelated to their name (or display name).

**Comment by brockallen** [comment]
To reset here -- their `UserNameClaimType` is what's used to set the `User.Identity.Name` property. By default they use the "username" claim type and they use the `User.Username` value, which is what's all wrong. This is why this library is using the `name` claim type instead, which makes much more sense. Unfortunately if you want a non-`Username` value, you have to do this rework manually yourself in a custom `IUserClaimsPrincipalFactory`

**Comment by brockallen** [comment]
Maybe this library should also register a custom `UserClaimsPrincipalFactory` that remove the username automatically?

**Comment by brockallen** [comment]
Ok, I have provided this: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/rc2/src/IdentityServer4.AspNetIdentity/UserClaimsFactory.cs

Feedback welcome. This should address the issue.
