### ISSUE TITLE
JavaScript Oidc Client - unauthorized_client Error

### ISSUE THREAD

**Issue by Valermus** [IdentityServer/IdentityServer4.AspNetIdentity#16]
When trying to interact with Host(http://localhost:1941) from JavaScript Oidc Client (http://localhost:7017/), recieving an **unauthorized_client Error** because JavaScript Oidc Client redirects to http://localhost:7017/callback.html

https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/Host/Configuration/Clients.cs at line 262-263 **http://localhost:7017/callback.html** should be added to prevent this error imho.

Maybe forgotten or there is something else i failed to grasp?

**Comment by brockallen** [comment]
Feel free to submit a PR to fix this.
