### ISSUE TITLE
Using AspNetIdentity along with External Login Examples

### ISSUE THREAD

**Issue by JChaneyGuardian** [IdentityServer/IdentityServer4.AspNetIdentity#18]
I was working through the Quick Start example for IdentityServer4 (Thank you!), and, I got to 6_aspnet_identity, and, got it working just fine. I then tried to add the External Provider examples, Google and demo.identityserver.io, to the new IdentityServerWithAspNetIdentity project. When I try to use either External Provider the call to _signInManager.GetExternalLoginInfoAsync() in AccountController.ExternalLoginCallback() always returns null.

I copied the code from the original IdentityServer project's AccountController.ExternalLoginCallback() to read the info and it is able to pull the information and it is working to get the login information from Google.

I've walked through the instructions on setting up the external providers from the QuickStart as well as from step 4 instructions. I've tried changing the order of when things are registered in Startup.Configuration(), but, I just am not getting anywhere with this.

I know it's probably something I'm just not understanding, and, I am hoping someone can help me out.

The attached ZIP contains my Startup.cs, Config.cs, Program.cs, AccountController.cs and project.json.

It also contains a Word Document that I pasted screen shots from Firebug with the request/response headers from the google signon and ExternalCallback calls for both the original setup working with the InMemory IdentityServer Quick Start and the ASPNetIdentity version that is not working.

[IdenityServerWithAspNetIdentity.Setup.zip](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/files/602002/IdenityServerWithAspNetIdentity.Setup.zip)

Thanks for any help or advice you can give.

Jeff Chaney

**Comment by brockallen** [comment]
I don't have time to look though your code, but make sure you're using the sample "SignIn" type for both the ASP.NET Identity config and the social providers.

**Comment by Developer-Kostas** [comment]
AccountController.ExternalLoginCallback() always returns null because it doesn't get the user id correctly. 

On your AccountController switch the method implementation of ` private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }`

to this `  private Task<ApplicationUser> GetCurrentUserAsync()
        {
           var id = HttpContext.User.Claims.ToList().FirstOrDefault(c => c.Type == "sub")?.Value;
            return id == null ? Task.FromResult<ApplicationUser>(null) : FindByIdAsync(id);
        }`

**Comment by Developer-Kostas** [comment]
Try this in StartUp.cs  
`

            services.AddIdentity<ApplicationUser, IdentityRole>(config => {
 config.Cookies.ExternalCookie = new CookieAuthenticationOptions {
                    AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,

                    AutomaticAuthenticate = false,
                    AutomaticChallenge = false
                };
  })`

**Comment by jeffchaney1** [comment]
Moving the setup of the CookieAuthenticationOptions into the ConfigureSevices() under services.AddIdentity() worked.  Thank you very much.  

```
            services.AddIdentity<ApplicationUser, IdentityRole>(
            // Added the following lines based on email from Developer-Kostas
                config => {
                config.Cookies.ExternalCookie = new CookieAuthenticationOptions
                {
                    AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,

                    AutomaticAuthenticate = false,
                    AutomaticChallenge = false
                };
            }
            // ********************************************************************
                )
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
```

I left the code in Configure() that calls UseCookieAuthentication().  Do I still need that?

```
            // NOTE: THE FOLLOWING CAME FROM https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/dev/README.md
            // cookie middleware for temporarily storing the outcome of the external authentication
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                //AutomaticAuthenticate = false,
                //AutomaticChallenge = false
            });
```

**Comment by Konstantinos-Val** [comment]
@jeffchaney1  I don't think app.UseCookieAuthentication() is needed anymore. You are calling app.UseIdentity(), see the source of the extension [here](https://github.com/aspnet/Identity/blob/5480aa182bad3fb3b729a0169d0462873331e306/src/Microsoft.AspNetCore.Identity/BuilderExtensions.cs),  that takes care of setting the ExternalCookieAuthenticationScheme we set on AddIdentity().

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by JChaneyGuardian** [comment]
Yes.  All good.  Thank you for your time and answers.  :)
