### ISSUE TITLE
ProfileService is not called

### ISSUE THREAD

**Issue by siberianguy** [IdentityServer/IdentityServer4.AspNetIdentity#20]
I setup AspNetIdentity integration for IdentityServer4 and everything works great so far besides I don't get user claims and role claims as part of authorization code. It seems like ProfileService is not called at all. Is there anything specific I should do to make ProfileService (the one implemented in the library) called?

I found [this](https://github.com/IdentityServer/IdentityServer4/issues/458) post that seems relevant. It says you need to use a scope that has additional claims but I'm not sure what it practically means in case of AspNetIdentity integration.

**Comment by leastprivilege** [comment]
Check the docs on identity resources and claims. Also check the quickstart that uses ASP.NET identity.

**Comment by dmostert** [comment]
Please be more specific on documentation that I need to refer to- I'm facing the same issue.

**Comment by leastprivilege** [comment]
https://identityserver4.readthedocs.io/en/release/configuration/resources.html

**Comment by siberianguy** [comment]
Honestly I read that and I feel completely lost. Documentation fails to explain why we need both IdentityResource and ApiResources, what exactly we need to specify to get ProfileService called, etc.

**Comment by dmostert** [comment]
Update: I managed to get it to work. I did 2 things:
1) Include the latest version of IdentityServer4 nuget package (I only refereced IdentityServer4.AspNetIdentity which refecrences v1 of IdentityServer4
2) Removed `scope` from my request

HTH.

**Comment by leastprivilege** [comment]
Did you try the quickstarts - they might be easier to digest than the docs. Ultimately we are implementing the specs. So reading that might help as well - and:

https://identityserver4.readthedocs.io/en/release/intro/terminology.html

**Comment by siberianguy** [comment]
@leastprivilege, could you please hint what are the criteria that make ProfileService called? Has it something to do with specifying Profile IdentityResource or something like that?

**Comment by leastprivilege** [comment]
the profile service is always called when claims for tokens are needed.

**Comment by siberianguy** [comment]
Okay, now I got the reason of misunderstanding. I expected ProfileService just automatically adds all the Claims to the token. But ProfileService receives all the claims but adds to the token only those specified in UserClaims in ApiResource. Right?

The problem is I use Claims for security and I really need to get all the Claims from ProfileService to the token. I can not specify them in UserClaims as the nature of security Claims is dynamic. I believe there was something like "AddAllClaims" in IdentityServer3. Sounds like what I need. Is there anything similar in IdentityServer4?

**Comment by leastprivilege** [comment]
If you need custom behavior - implement your own profile service. It's easy.

**Comment by siberianguy** [comment]
So it all comes down to [this line](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/ProfileService.cs#L31) that adds only filtered (requested) claims to a token. So what I basically need to do is to say: "hey, just add all the claims, bro". IdentityServer3 used to have a way to do that (if I'm not mistaken). Is there anything like that in IdentityServer4?

**Comment by leastprivilege** [comment]
no.

**Comment by siberianguy** [comment]
:) But why? Is it considered a bad practice?

**Comment by siberianguy** [comment]
> the profile service is always called when claims for tokens are needed.

A small correction. ProfileService is always called but default implementation of ProfileService filters only the claims you requested.

**Comment by siberianguy** [comment]
Eventually I just created a custom ProfileServce:

```
    public class ProfileService : ProfileService<IdentityUser>
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUserClaimsPrincipalFactory<IdentityUser> _claimsFactory;

        public ProfileService(UserManager<IdentityUser> userManager, IUserClaimsPrincipalFactory<IdentityUser> claimsFactory) : base(userManager, claimsFactory)
        {
            _userManager = userManager;
            _claimsFactory = claimsFactory;
        }

        public override async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);
            var principal = await _claimsFactory.CreateAsync(user);
            context.IssuedClaims.AddRange(principal.Claims);
        }
    }
```

It's basically a copy-paste of default ProfileService's GetProfileDataAsync where the last line Adds all the claims instead of filtering the ones you requested.

P. S. It's important to add `.AddProfileService<ProfileService>()` in Startup after `.AddAspNetIdentity<IdentityUser>()`.

**Comment by brockallen** [comment]
> instead of filtering the ones you requested

While this isn't technically wrong, it's not the normal use based on the design. You can have an infinite number of claims, but client might only want a subset. Thus the design.

**Comment by brockallen** [comment]
All set on this issue? Can we close?

**Comment by siberianguy** [comment]
Thanks! Closing it.
