### ISSUE TITLE
Replacing TestUserStore with AspNetIdentity

### ISSUE THREAD

**Issue by siberianguy** [IdentityServer/IdentityServer4.AspNetIdentity#21]
I'm in the process of migrating 5_HybridFlowAuthenticationWithApiAccess from IdentityServer4 samples to AspNetIdentity and I'm confused what I'm supposed to do with TestUserStore. At first I thought AspNetIdentity integration implements UserStore but it doesn't seem to be the case. Any hint?

**Comment by brockallen** [comment]
TestUserStore can be removed. It's just a class that was being used by the UI.
