### ISSUE TITLE
When har these repos released

### ISSUE THREAD

**Issue by inongogo** [IdentityServer/IdentityServer4.AspNetIdentity#22]
I'm wondering if thes project is supposed to be released at the same time as [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) or if it has another release cycle. 

I noticed that [IdentityServer4.AspNetIdentity](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity) and [IdentityServer4.EntityFramework](https://github.com/IdentityServer/IdentityServer4.EntityFramework)  are dependent on [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) and they are referencing an older version of it than is currently released.

**Comment by brockallen** [comment]
We update and release them on their own as appropriate. You can always update your consuming app to the latest NuGets of IdentityServer, despite this library using an older reference (subject to semver, as always).
