### ISSUE TITLE
Handling Two-Factor Authentication

### ISSUE THREAD

**Issue by Singularity222** [IdentityServer/IdentityServer4.AspNetIdentity#24]
Hey there, I have a question about supporting two-factor authentication while using the resource owner password flow with identity server 4 and ASP.NET Core Identity. The client application would be a SPA. In my application I have implemented the IResourceOwnerPasswordValidator interface in order to validate user token requests. I was looking into adding two-factor authentication to my application and this is what I came up with:

```
      /// <summary>
      /// Validates the username and password to authenticate a user by using methods 
      /// provided by ASP.NET Core identity.
      /// </summary>
      /// <param name="context">The identity server validation context.</param>
      /// <returns>A Task.</returns>
      public async Task ValidateAsync(ResourceOwnerPasswordValidationContext context)
      {
         ManticoreUser user = await userManager.FindByNameAsync(context.UserName);

         if (user != null)
         {
            SignInResult result = await signInManager.CheckPasswordSignInAsync(user, context.Password, true);

            if (result.Succeeded && user.TwoFactorEnabled)
            {
               string code = context.Request.Raw["code"];

               // Currently, two-factor authentication via phone is available.
               bool isTwoFactorCodeValid = await userManager.VerifyTwoFactorTokenAsync(user, "Phone", code);

               if (isTwoFactorCodeValid)
               {
                  await SetContext(user, context);
                  return;
               }
            }
            else if (result.Succeeded)
            {
               await SetContext(user, context);
               return;
            }
         }

         const string Description = "The username or password provided is invalid or the two-factor code cannot be verified.";

         context.Result = new GrantValidationResult(TokenRequestErrors.InvalidGrant, Description);
      }

      private async Task SetContext(ManticoreUser user, ResourceOwnerPasswordValidationContext context)
      {
         var sub = await userManager.GetUserIdAsync(user);
         context.Result = new GrantValidationResult(sub, OidcConstants.AuthenticationMethods.Password);
      }
```
When passing the username and password to the token endpoint, I'm also passing an extra 'code' parameter. If the user has two factor enabled, the code will be retrieved and validated. I was curious if there could be issues with this, or it could be something we could integrate into this repository. It's rough at the moment for sure, but I thought it was worth bringing up.

Thanks

**Comment by leastprivilege** [comment]
You would need to use a web-based flow for that. 

Or come up with your own custom protocol.

**Comment by Singularity222** [comment]
So you think using the Resource Owner Password grant type wouldn't work here? I don't see why not as I have control of the IResourceOwnerPasswordValidator implementation. My single page application could determine when it needs to send the code. What issues would I run into doing it this way?

**Comment by leastprivilege** [comment]
I don't know - give it a try and let me know.
