### ISSUE TITLE
SecurityStampValidatorCallback.UpdatePrincipal() throws away claims if more than one exists with the same type name

### ISSUE THREAD

**Issue by mackie1001** [IdentityServer/IdentityServer4.AspNetIdentity#26]
In our implementation we use multiple "amr" claims in our ClaimsPrincipal to store which methods the user used to authenticate when multi-factor authentication is used (e.g. "pwd" and "otp"). It would appear that the logic inside UpdatePrincipal assumes no duplicate claim types and we lose the second "amr" claim when the security stamp check kicks in an renews the current principal. Can can work around this but I figured it was worth reporting.

**Comment by mackie1001** [comment]
After a bit of testing it looks like `var currentClaimsToKeep = context.CurrentPrincipal.Claims.Where(x => !newClaimTypes.Contains(x.Type));` just needs to be enumerated before its used. The contents of the results is actually changing as it's iterated over.

**Comment by brockallen** [comment]
Ok, I'll take a look as soon as I can. Thanks

**Comment by brockallen** [comment]
Fixed for 2.0. Thanks.
