### ISSUE TITLE
Upgrade to AspNet Core Identity 2.0?

### ISSUE THREAD

**Issue by hikalkan** [IdentityServer/IdentityServer4.AspNetIdentity#29]
AspNet Core Identity 2.0 has some breaking changes (moved most types from microsoft.aspnetcore.identity to Microsoft.Extensions.Identity.Core for example). Have you planned to work on that?
Thanks.

**Comment by brockallen** [comment]
It will all be done as part of this: https://github.com/IdentityServer/IdentityServer4/issues/1055

**Comment by easyfast** [comment]
Yes, Good idear.AspNet Core Identity 2.0  is future development directions, We shoud be Migrate to this version.

**Comment by weitzhandler** [comment]
I can't upgrade to 2.0: #1625.
