### ISSUE TITLE
IdentityServer4.AspNetIdentity ASP. Net Core 2

### ISSUE THREAD

**Issue by Mewriick** [IdentityServer/IdentityServer4.AspNetIdentity#30]
Hello, 
when will be IdentityServer4.AspNetIdentity prepared for working with ASP. Net Core 2 ?

**Comment by brockallen** [comment]
As soon as we can get to it.

**Comment by SychevIgor** [comment]
@brockallen it will be really awesome, if it will be available... it's primary blocker from updating https://github.com/dotnet-architecture/eShopOnContainers to .net core 2.0
