### ISSUE TITLE
TypeLoadException IdentityOptions with Core 2.0

### ISSUE THREAD

**Issue by lasrol** [IdentityServer/IdentityServer4.AspNetIdentity#31]
I am in the process of upgrading to Core 2.0, and at runtime the application crashes. 

> TypeLoadException: Could not load type 'Microsoft.AspNetCore.Builder.IdentityOptions' from assembly 'Microsoft.AspNetCore.Identity, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

i assume its because you are referencing Identity  version 1.1.1. You plan on upgrading? are there any known workaround or should i just clone, upgraded and build the nuget myself?

**Comment by brockallen** [comment]
Of course we plan on it, but we do this in our free time. It'll be done when it's done.

**Comment by lasrol** [comment]
No problem, i understand. Just curious what kind of plan you had. Would you be interested in a PR? I have updated with the required changes and it works fine in my project. There is just a minor issue with the host project, but if you want a PR i will update that as well.

**Comment by brockallen** [comment]
I happen to be home (and not traveling) for the next two week, during which time I'll be working on it.
