### ISSUE TITLE
IdentityServer4.AspNetIdentity ASP. Net Core 2 RTM

### ISSUE THREAD

**Issue by fpragana** [IdentityServer/IdentityServer4.AspNetIdentity#35]
Hi, i have a problem when include AddAspNetIdentity<IdentityUser>() on services.AddIdentityServer() using the follow  library versions:

Microsoft.NETCore.App .  2.0.0
Microsoft.AspNetCore.All . 2.0.0
IdentityServer4 .  2.0.0-preview4
IdentityServer4.AspNetIdentity .  1.0.1

```
System.TypeLoadException occurred
  HResult=0x80131522
  Message=Could not load type 'Microsoft.AspNetCore.Builder.IdentityOptions' from assembly 'Microsoft.AspNetCore.Identity, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensions.AddAspNetIdentity[TUser](IIdentityServerBuilder builder, String authenticationScheme)
   at Auth.Startup.ConfigureServices(IServiceCollection services) in Startup.cs:line 51
```

**Comment by rizamarhaban** [comment]
@fpragana try look from my workaround while they upgrading the modules to support ASP.NET Core 2.0. [https://github.com/rizamarhaban/IdentityServer4Demo](https://github.com/rizamarhaban/IdentityServer4Demo)

**Comment by jimmymain** [comment]
I have tried using version 2.0.0-rc1.

When attempting to use the issued bearer token, I am being redirected to the login page.
When attempting to login using user/password (cookie) I get the error.

> InvalidOperationException: sub claim is missing
IdentityServer4.IdentityServerPrincipal.AssertRequiredClaims(ClaimsPrincipal principal)
IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal)
IdentityServer4.Hosting.IdentityServerAuthenticationService+<SignInAsync>d__7.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.SignInManager+<SignInAsync>d__30.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
Microsoft.AspNetCore.Identity.SignInManager+<SignInOrTwoFactorAsync>d__52.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.SignInManager+<PasswordSignInAsync>d__33.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.SignInManager+<PasswordSignInAsync>d__34.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
FormWorkx.Web.Controllers.AccountController+<Login>d__19.MoveNext() in AccountController.cs
```
var result = await this._signInManager.PasswordSignInAsync(
```

**Comment by brockallen** [comment]
We released an IdentityServer4.AspNetIdentity 2.0.0-rc1 yesterday. Try that, please.

**Comment by fpragana** [comment]
@brockallen it's work...  Tks..
