### ISSUE TITLE
Release 2.0.0 - RC1 seems to have a login error.

### ISSUE THREAD

**Issue by jimmymain** [IdentityServer/IdentityServer4.AspNetIdentity#36]
I have tried using version 2.0.0-rc1.

I have managed to obtain tokens, however...

- When attempting to use the issued bearer token in an API using the `Authorization` header, I am being redirected to the login page.

- When attempting to login using user/password (cookie) I get the error.

> InvalidOperationException: sub claim is missing
IdentityServer4.IdentityServerPrincipal.AssertRequiredClaims(ClaimsPrincipal principal)
IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal)
IdentityServer4.Hosting.IdentityServerAuthenticationService+d__7.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.SignInManager+d__30.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
Microsoft.AspNetCore.Identity.SignInManager+d__52.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.SignInManager+d__33.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.SignInManager+d__34.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
FormWorkx.Web.Controllers.AccountController+d__19.MoveNext() in AccountController.cs
var result = await this._signInManager.PasswordSignInAsync(

**Comment by Ciantic** [comment]
I'm getting same issue, I have this in the services:

```C#
services
    .AddIdentity<ApplicationUser, ApplicationRole>()
    .AddEntityFrameworkStores<UserServiceContext>();
    //.AddDefaultTokenProviders();

services.AddAuthentication().AddJwtBearer(o =>
{
    o.Audience = "http://localhost:5002/";
    o.Authority = "http://localhost:5002/";
});


services.AddIdentityServer()
        .AddDeveloperSigningCredential()
        .AddInMemoryIdentityResources(new List<IdentityResource>
        {
            new IdentityResources.OpenId(),
            new IdentityResources.Profile(),
        })
        .AddInMemoryApiResources(new List<ApiResource>
        {
            new ApiResource("api", "API")
        })
        .AddInMemoryClients(new List<Client>
        {
        // OpenID Connect implicit flow client (MVC)
        new Client
        {
            ClientId = "example-client",
            ClientName = "Example Client",
            AllowedGrantTypes = GrantTypes.Implicit,
            AllowAccessTokensViaBrowser = true,
            RequireConsent = false,
            RedirectUris = { "http://localhost:5002/o2c.html" },
            PostLogoutRedirectUris = { "http://localhost:5002/o2c-logout.html" },

            AllowedScopes = {
                IdentityServerConstants.StandardScopes.OpenId,
                IdentityServerConstants.StandardScopes.Profile
            }
        }
        });
```

**Comment by brockallen** [comment]
So you're hosting IdSvr and the login UI and the API all in the same project/host? That's not something we've tested for, since it's not something we typically recommend.

**Comment by jansivans** [comment]
@brockallen I am doing this - hosting everything in one solution. Reason for this is that I needed to combine IdentityServer4.EntityFramework with Asp.Net.Identity, extend some IdentityServer's entities and write my own login UI.

**Comment by Ciantic** [comment]
I'm doing this as well, in fact I thought it's great idea! I've used openiddict before, but since this has the .NET Foundation stamp decided to try this.

**Comment by jimmymain** [comment]
I think a lot of developers will be building angular 1/2/4 front ends. They need a bearer token solution to a dotnetcore back end, all in the same solution. Resource owner password credentials flow is likely - at least initially. I would imagine it being an extremely common workflow.

**Comment by Ciantic** [comment]
Since this is not a recommended way to use the IdentityServer4, I suggest everyone here look at [OpenIddict](https://github.com/openiddict/openiddict-core). It has a bit more involved API, but it can be plugged in same project as rest of the .NET application.

Maybe the IdentityServer as name suggest should be it's own server, not a lightweight solution that can be added to any app.

**Comment by lasrol** [comment]
I was missing  `.AddIdentityServer(); ` when configuring my aspnet identity services, that caused my application to crash with 

> InvalidOperationException: sub claim is missing

 when i tried to login with the signInManager. 

Example: 
```
services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddIdentityServer();
```

**Comment by jimmymain** [comment]
@lasrol shot!
works perfectly now.
@Ciantic - I kind of agree, but I have it working now (thanks to @lasrol).
all in the same web application - and it's great.

I am going to carry on using IdentityServer4 as I am, if it's ever impossible to make it work, I will go with a far simpler solution and roll my own like this https://wildermuth.com/2017/08/19/Two-AuthorizationSchemes-in-ASP-NET-Core-2

**Comment by jimmymain** [comment]
Are you chaps getting the roles included in the claims when roles are added via user manager.
I have roles in the database, but they are not being loaded into the claims.

Does anyone have some tips?

**Comment by rizamarhaban** [comment]
@brockallen,

I also get this error ```InvalidOperationException: sub claim is missing``` when upgraded to RC1. And here is my solution. In the ```IdentityServerBuilderExtensions.cs``` file, the claims were missing,

``` csharp
    builder.Services.Configure<IdentityOptions>(options =>
    {
        options.ClaimsIdentity.UserIdClaimType = JwtClaimTypes.Subject;
        options.ClaimsIdentity.UserNameClaimType = JwtClaimTypes.Name;
        options.ClaimsIdentity.RoleClaimType = JwtClaimTypes.Role;
    });
```

I added back to method, and here is what I have changed to make it work;

``` csharp
    public static IIdentityServerBuilder AddAspNetIdentity<TUser>(this IIdentityServerBuilder builder)
        where TUser : class
    {
        builder.Services.Configure<IdentityOptions>(options =>
        {
            options.ClaimsIdentity.UserIdClaimType = JwtClaimTypes.Subject;
            options.ClaimsIdentity.UserNameClaimType = JwtClaimTypes.Name;
            options.ClaimsIdentity.RoleClaimType = JwtClaimTypes.Role;
        });

        builder.AddResourceOwnerValidator<ResourceOwnerPasswordValidator<TUser>>();
        builder.AddProfileService<ProfileService<TUser>>();

        return builder;
    }
```

And on the ```ProfileService.cs``` file, ```GetProfileDataAsync(ProfileDataRequestContext context)``` method, I changed the ```AddRequestedClaims(...)``` to ```FilterClaims(...)```, shows like this;

``` csharp
    public virtual async Task GetProfileDataAsync(ProfileDataRequestContext context)
    {
        var sub = context.Subject.GetSubjectId();
        var user = await _userManager.FindByIdAsync(sub);
        var principal = await _claimsFactory.CreateAsync(user);
        context.FilterClaims(principal.Claims);
    }
```

However, I don't know whether that will be the correct solution.

**Comment by jimmymain** [comment]
I solved it here: https://stackoverflow.com/questions/46091301/roles-not-being-populated-by-addjwtbearer-using-identityserver4-and-dotnetcore-2/46094800#46094800

**Comment by damienbod** [comment]
I having problems getting rc1 to work. The solution from @rizamarhaban is cool, but I think, this should work out of the box wiithout the need for extensions. I also have problems with the AuthorizationScheme.

@brockallen @leastprivilege Thoughs?

**Comment by gato-negro** [comment]
Same error ("InvalidOperationException: sub claim is missing") for me with identityserver4 version 2.0.0-rc1 and asp net core 2.

Issue was resolved by adding the 3rd parameter (claimTypes) in the new ApiResource constructor method included in link provided by @jimmymain:

public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource(
                    AppConstants.APIClientId, AppConstants.APIClientName,
                    new[]{                   
                        // exhaustive list of claims in a new
                        // dotnetcore 2.0 MVC application.
                        "nbf",
                        "exp",
                        "iss",
                        "aud",
                        "aud",
                        "client_id",
                        "sub",
                        "auth_time",
                        "idp",
                        "AspNet.Identity.SecurityStamp",
                        ClaimTypes.Role,  
                        "preferred_username",
                        "name",
                        "email",
                        "email_verified",
                        "scope",
                        "amr"
                    })
            };
        }

**Comment by cbfrank** [comment]
basically, @rizamarhaban  solution works, but I found ID4 RC1 has already provided the extension method for this.
In ConfigureServices, after call services.AddIdentity, append another call AddIdentityServer i.e.
`services.AddIdentity<TUser, TRole>(opts=>{****}).AddIdentityServer()`

There are tow `AddIdentityServer`, one is for IdentityBuilder and one is for IServiceCollection, both are required for host an Identity Server

**Comment by brockallen** [comment]
For those of you that had problems co-hosting IdentityServer and an API in the same host, here's a sample: https://github.com/brockallen/IdentityServerAndApi

Also, any other updates on this issue? I can't seem to repro your issue, and I have a vague suspicion that it's related not to IdentityServer, but rather the changes in authentication in ASP.NET Core 2.0.

**Comment by brockallen** [comment]
I updated the ASP.NET Identity Quickstart just now, and everything seems to be working properly. Check the latest code and see what's different in your project.

https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/6_AspNetIdentity

Also, QS docs updated too: http://docs.identityserver.io/en/dev/quickstarts/6_aspnet_identity.html

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by ByteNuts** [comment]
I'm getting the same exception from 1st post, but I'm not using ASP.NET Identity, but trying to use IS4 memory stores with Azure AD authentication through Office 365 subscription.

I configured IS4 has in this [sample repo](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/5_HybridFlowAuthenticationWithApiAccess/src/QuickstartIdentityServer), with the changes detailed below. 

When I authenticate on Office Portal webpage, I get redirected back and when debugging OpenID event *OnTokenValidated*, I get the *SecurityToken* containing all the expected information (22 properties), with *sub* included.
The properties are: *alg*, *typ*, *x5t*, *kid*, *aud*, *iss*, *iat*, *nbf*, *exp*, *aio*, *amr*, *family_name*, *given_name*, *ipaddr*, *name*, *nonce*, *oid*, *sub*, *tid*, *unique_name*, *upn*, *ver*.

On the next event *OnTicketReceived*, the Identity is correctly filled with an authenticated user, but the user claims contain only 10 properties, and *sub* isn't included.
The properties are: *aio*, *authnmethodsreferences*, *surname*, *givenname*, *name*, *objectidentifier*, *nameidentifier*, *tenantid*, *name* and *upn*.

Looking at logs, the only relevant part is a debug message stating that a CORS request was rejected.

Am I missing some extra configuration?


**Log partial**
```
2017-10-03 15:12:28.475 +01:00 [Information] Request starting HTTP/1.1 POST http://localhost:5000/signin-oidc application/x-www-form-urlencoded 1888
2017-10-03 15:12:28.495 +01:00 [Debug] CORS request made for path: "/signin-oidc" from origin: "null" but rejected because invalid CORS path
2017-10-03 15:12:28.506 +01:00 [Debug] Connection id ""0HL8AD2U45VM4"", Request id ""0HL8AD2U45VM4:00000003"": started reading request body.
2017-10-03 15:12:28.509 +01:00 [Debug] Connection id ""0HL8AD2U45VM4"", Request id ""0HL8AD2U45VM4:00000003"": done reading request body.
2017-10-03 15:12:29.458 +01:00 [Debug] Updating configuration
2017-10-03 15:12:29.461 +01:00 [Debug] Received 'id_token'
2017-10-03 15:12:31.326 +01:00 [Debug] Augmenting SignInContext
2017-10-03 15:12:31.400 +01:00 [Error] An unhandled exception has occurred while executing the request
System.InvalidOperationException: sub claim is missing
```

**Startup.cs**
```
services.AddIdentityServer()
    .AddDeveloperSigningCredential()
    .AddInMemoryIdentityResources(Config.GetIdentityResources())
    .AddInMemoryApiResources(Config.GetApiResources())
    .AddInMemoryClients(Config.GetClients())
    .AddTestUsers(Config.GetUsers());
services.AddAuthentication()
    .AddAzureAd(options => Configuration.Bind("LiveAd", options));
```

**AzureAdAuthenticationBuilderExtensions.cs** (copied from VS2017 templates using authentication "Work or School Accounts" - "Cloud - Single Organization")
```
public static class AzureAdAuthenticationBuilderExtensions
{
public static AuthenticationBuilder AddAzureAd(this AuthenticationBuilder builder)
    => builder.AddAzureAd(_ => { });

public static AuthenticationBuilder AddAzureAd(this AuthenticationBuilder builder, Action<AzureAdOptions> configureOptions)
{
    builder.Services.Configure(configureOptions);
    builder.Services.AddSingleton<IConfigureOptions<OpenIdConnectOptions>, ConfigureAzureOptions>();
    builder.AddOpenIdConnect(opts =>
    {
        opts.Events = new OpenIdConnectEvents
        {
            OnAuthorizationCodeReceived = ctx =>
            {
                return Task.CompletedTask;
            },
            OnUserInformationReceived = ctx =>
            {
                return Task.CompletedTask;
            },
            OnRedirectToIdentityProvider = ctx =>
            {
                return Task.CompletedTask;
            },
            OnMessageReceived = ctx =>
            {
                return Task.CompletedTask;
            },
            OnTicketReceived = ctx =>
            {
                return Task.CompletedTask;
            },
            OnTokenResponseReceived = ctx =>
            {
                return Task.CompletedTask;
            },
            OnTokenValidated = ctx =>
            {
                return Task.CompletedTask;
            }
        };
    });
    return builder;
}
```

**ConfigureAzureOptions.cs**
```
private class ConfigureAzureOptions : IConfigureNamedOptions<OpenIdConnectOptions>
{
    private readonly AzureAdOptions _azureOptions;

    public ConfigureAzureOptions(IOptions<AzureAdOptions> azureOptions)
    {
        _azureOptions = azureOptions.Value;
    }

    public void Configure(string name, OpenIdConnectOptions options)
    {
        options.ClientId = _azureOptions.ClientId;
        options.Authority = $"{_azureOptions.Instance}{_azureOptions.TenantId}";
        options.UseTokenLifetime = true;
        options.CallbackPath = _azureOptions.CallbackPath;
        options.RequireHttpsMetadata = false;
    }

    public void Configure(OpenIdConnectOptions options)
    {
        Configure(Options.DefaultName, options);
    }
}
```

**appsettings.json**
```
  "LiveAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "my.customdomain.com",
    "TenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "ClientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "CallbackPath": "/signin-oidc"
  }
```

**Comment by ByteNuts** [comment]
Ok... Just needed to ask to get the solution... :sigh:

Was missing the OpenId schemas config.

```
options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
options.SignOutScheme = IdentityServerConstants.SignoutScheme;
```

Thanks anyway.

**Comment by Triwaters** [comment]
I ran into this error message, banged my head against the wall for a day (and some of a night), restarted new projects multiple times, trying to reduce the problem to its simplest case (or build up a working solution back to the point of failure)... ended up that I was working off of what appears to have been bad code in the online docs. I used this...

`
// configure identity server with in-memory stores, keys, clients and scopes
services.AddIdentityServer()
.AddDeveloperSigningCredential()
//.AddTestUsers(Config.GetUsers())
.AddAspNetIdentity<ApplicationUser>()
`
instead of this...

`
// configure identity server with in-memory stores, keys, clients and scopes
services.AddIdentityServer()
    .AddDeveloperSigningCredential()
    .AddTestUsers(Config.GetUsers())
    // this adds the config data from DB (clients, resources)
`
as demonstrated here: http://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html

I've submitted a PR to remedy that, pending confirmation that it's not me who's confused on this one.

**Comment by brockallen** [comment]
Why would you add test users if you were using ASP.NET Identity?

**Comment by Triwaters** [comment]
I wasn't adding test-users so much as (I thought) pasting the right code from the right spot to match what I *thought* was the last lap... a fully implemented data-driven instance of IdentityServer using ASP.NET Identity for user storage. Per your comments elsewhere I now see how I was misreading your documentation.  (And once you see it, you wonder why you didn't notice the problem sooner!) But someone else might make the same mistake, so I'll leave these comments here.

**Comment by brockallen** [comment]
Fair enough. Thanks for the comments then :)
