### ISSUE TITLE
User.Identity.Name is null after successful authentication.

### ISSUE THREAD

**Issue by jimmymain** [IdentityServer/IdentityServer4.AspNetIdentity#38]
The name property is not correctly set to the name of the user.
Claims are correct and present, but the user name is null, as a simple controller method indicates.

```
        [Authorize]
        [HttpGet("user")]
        public object UserDetail() {
                this.User.Identity.Name == null
        }
```

Issue also getting some attention on [stackoverflow](https://stackoverflow.com/questions/46274422/user-doesnt-seem-authenticated-in-the-pipline-insideuse-in-dotnetcore-2-0?noredirect=1#comment79546745_46274422).

**Comment by brockallen** [comment]
Did you set the name claim type setting?

**Comment by brockallen** [comment]
I updated the ASP.NET Identity Quickstart just now, and in my testing `Name` is properly assigned. Check the latest code and see what's different in your project.

https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/6_AspNetIdentity

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by alaa9jo** [comment]
I think I'm facing a similar issue, I can reproduce it with Quickstart7_JavaScriptClient.sln Solution , here is the steps to reproduce the issue:

* I debug Api project, add breakpoint on method Get() within IdentityController
* Hit on "Call Api" button from Javascript client.
* The debugger stops on Get() method
* Notice that User.Identity.Name is null, also notice that User.Claims doesn't have claim "Name" or "Website"

I'm not really sure what is missing to make it work

**Comment by jimmymain** [comment]
Try ensure that you have all the claims you need...

``` c#
        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource(
                    Api,
                    "formworkx api",
                    new[]
                    {
                        "nbf",
                        "exp",
                        "iss",
                        "aud",
                        "aud",
                        "client_id",
                        "sub",
                        "auth_time",
                        "idp",
                        "AspNet.Identity.SecurityStamp",
                        ClaimTypes.Role,
                        ClaimTypes.Name,
                        ClaimTypes.Authentication,
                        ClaimTypes.GivenName,
                        ClaimTypes.Email,
                        ClaimTypes.Gender,
                        "preferred_username",
                        "name",
                        "email",
                        "email_verified",
                        "scope",
                        "amr"
                    })
            };
        }
```

and also ensure that the token is set correctly (this might not be required if the claims are correct above)
``` c#
        o.Events = new JwtBearerEvents
        {
              OnTokenValidated = this.TokenValidated
        };

        private Task TokenValidated(TokenValidatedContext context)
        {
            var user = new ClaimsPrincipal(new ClaimsIdentity(
                context.Principal.Claims, 
                "local",
                "name",
                ClaimTypes.Role));
            context.Principal = user;
            return Task.CompletedTask;
        }
```

**Comment by alaa9jo** [comment]
Thanks @jimmymain , It worked!
