### ISSUE TITLE
Session Timeout after 30minutes - SecurityStampValidationInterva

### ISSUE THREAD

**Issue by rezareAW** [IdentityServer/IdentityServer4.AspNetIdentity#39]
Originally I posted this https://github.com/IdentityServer/IdentityServer4/issues/1562 but it was suggested I move to this thread.

After I login using any of the flows of Implicity or Hybrid and leaving the browser window open I am logged out after 30mins. The logs seem to indicate a session timeout.

I have read up on this and it appears it could potentially be related to the SecurityStamp of Identity becoming invalid, however everything I read indicates this should only occur when the user changes security details i.e. password. In my case this is not happening.

I have tried lots of things but can't seem to get past this issue in IdentityServer other than changing the SecurityStampValidationInterval to a high number.

Parts of my setup code include:

                      services.AddIdentity<IdentityUser, IdentityRole>(
                      options =>
                       {
                       options.Cookies.ApplicationCookie.AuthenticationScheme = cookieAuth.AuthenticationScheme;

                        // https://github.com/aspnet/Identity/issues/999
                        // https://github.com/aspnet/Identity/issues/1389
                        // https://stackoverflow.com/questions/45825684/asp-net-core2-0-user-auto-logoff-after-20-30-min
                        // https://github.com/aspnet/Identity/issues/958
                        options.SecurityStampValidationInterval = TimeSpan.FromMinutes(10); //TimeSpan.FromHours(12);

                        // Password requirements as per Gemini item - ATX-239349  Sys2 - Identity server
                        options.Password.RequiredLength = 8;
                        options.Password.RequireUppercase = true;
                        options.Password.RequireLowercase = true;
                        options.Password.RequireNonAlphanumeric = true; 
                        options.Password.RequireDigit = true;
                    })
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddPasswordValidator<Features.Account.PasswordValidator<IdentityUser>>();

        var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

        services.AddIdentityServer(
                    options => { options.Authentication.AuthenticationScheme = cookieAuth.AuthenticationScheme; })
                .AddOperationalStore(
                    builder => builder.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationsAssembly)))
                .AddConfigurationStore(
                    builder => builder.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationsAssembly)))
                .AddAspNetIdentity<IdentityUser>()
                .AddTemporarySigningCredential();
        
        // please note that ideally if we want to persist the memory cache and the data protection information across multple instances
        // of the application we need to consider storing these in the database.  However at the moment we are a single instance so this approach is acceptable
        services.AddDistributedMemoryCache();
        services.AddSession(options =>
        {
            options.CookieHttpOnly = true;
            options.IdleTimeout = TimeSpan.FromMinutes(120);
        });

        services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(appSettings.PersistedCacheDirectory))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(appSettings.PersistedCacheDuration));

Relevant parts of the log file

2017-09-26 07:09:16.327 +13:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.AuthorizeEndpoint" for "/connect/authorize"
2017-09-26 07:09:16.329 +13:00 [Debug] Start authorize request
2017-09-26 07:09:16.331 +13:00 [Debug] AuthenticationScheme: "Identity.Application" was not authenticated.
2017-09-26 07:09:16.333 +13:00 [Debug] No user present in authorize request
2017-09-26 07:09:16.334 +13:00 [Debug] Start authorize request protocol validation

NOTE:
Looking at the AspNet Identity code that is responsible for Obtaining the security token from the SignInManager the code looks like:

 public virtual async Task<TUser> ValidateSecurityStampAsync(ClaimsPrincipal principal)
        {
            if (principal == null)
            {
                return null;
            }
            var user = await UserManager.GetUserAsync(principal);
            if (user != null && UserManager.SupportsUserSecurityStamp)
            {
                var securityStamp =
                    principal.FindFirstValue(Options.ClaimsIdentity.SecurityStampClaimType);
                if (securityStamp == await UserManager.GetSecurityStampAsync(user))
                {
                    return user;
                }
            }
            return null;
        }

My query is around the line as this by what I see would always return a null string?:

                var securityStamp =
                    principal.FindFirstValue(Options.ClaimsIdentity.SecurityStampClaimType);

**Comment by brockallen** [comment]
If the security stamp in the DB is changed, then the user must login again -- that's the semantics of the security stamp validator. If you don't want that, then disable it.

**Comment by rezareAW** [comment]
But it's not changing?  Or I'm doing nothing at all to change it.  All that is happening is I login and leave the website open for 30mins doing absolutely nothing.  Then the SecurityStampValidator kicks in and I get signed out.

I've tried looking through the code but can see no where where the Options.ClaimsIdentity.SecurityStampClaimType would be added to the ClaimsPrincipal so am assuming that is returning null and so invalidating the security stamp and so forcing the user to login.

Am I missing something here?  Do you need some further logging or information?

**Comment by brockallen** [comment]
So if it does not change, then ASP.NET Identity will re-issue a new cookie with fresh claims loaded from the DB. 

We provide a hook on that process to ensure we don't lose certain claims that are needed by IdentityServer (sub, idp, auth_time, etc).

**Comment by rezareAW** [comment]
ok so this line in SignInManager of AspNet Identity:

   var securityStamp =
                principal.FindFirstValue(Options.ClaimsIdentity.SecurityStampClaimType);

means on user login in our IdentityServer Host application we need to ensure the security stamp is included in the users principal so that the SignInManager code never returns null from _ValidateSecurityStampAsync_..

Would something like this then suffice in our AccountController Login method?

   var securityClaim = new Claim(new ClaimsIdentityOptions().SecurityStampClaimType,    identityUser.SecurityStamp);     
                    
                    await _events.RaiseAsync(new UserLoginSuccessEvent(identityUser.UserName, identityUser.Id, identityUser.UserName));
                    await HttpContext.Authentication.SignInAsync(identityUser.Id, identityUser.UserName, props, **securityClaim**);

**Comment by brockallen** [comment]
Given that you don't have it, I have a feeling you're overriding or replacing the built-in `IUserClaimsPrincipalFactory` -- is that possible?

**Comment by rezareAW** [comment]
I guess it's possible but I can't see where.  I took the original Host application and used that.  However I'm not running the 2.0 version so maybe it was changed and fixed in 2.0?  I'm still on 1.5.2.

This is my startup.cs which I don't think anything is out of the ordinary unless I'm doing things in the wrong order?.

```
public void ConfigureServices(IServiceCollection services)
{
	var appSettings = GetAppSettings();
	var connectionString = Configuration.GetConnectionString("IdentityContext");

	// ASP.NET Identity DbContext
	services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(connectionString));

	var cookieAuth = new CookieAuthenticationOptions();
	Configuration.GetSection("CookieAuthentication").Bind(cookieAuth);

	// ASP.NET Identity Registrations            
	services.AddIdentity<IdentityUser, IdentityRole>(
				options =>
				{
					options.Cookies.ApplicationCookie.AuthenticationScheme = cookieAuth.AuthenticationScheme;

					// Password requirements as per Gemini item - ATX-239349  Sys2 - Identity server
					options.Password.RequiredLength = 8;
					options.Password.RequireUppercase = true;
					options.Password.RequireLowercase = true;
					options.Password.RequireNonAlphanumeric = true; 
					options.Password.RequireDigit = true;
				})
		.AddEntityFrameworkStores<ApplicationDbContext>()
		.AddPasswordValidator<Features.Account.PasswordValidator<IdentityUser>>();

	var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

	services.AddIdentityServer(
				options => { options.Authentication.AuthenticationScheme = cookieAuth.AuthenticationScheme; })
			.AddOperationalStore(
				builder => builder.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationsAssembly)))
			.AddConfigurationStore(
				builder => builder.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationsAssembly)))
			.AddAspNetIdentity<IdentityUser>()
			.AddTemporarySigningCredential();
	
	services.AddDistributedMemoryCache();

	services.AddDataProtection()
			.PersistKeysToFileSystem(new DirectoryInfo(appSettings.PersistedCacheDirectory))
			.SetDefaultKeyLifetime(TimeSpan.FromDays(appSettings.PersistedCacheDuration));

	services.AddMvc();
	services.AddAntiforgery(p => p.SuppressXFrameOptionsHeader = false);
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
	var appSettings = GetAppSettings();

	loggerFactory.AddConsole();
	loggerFactory.AddDebug();

	var serilog = new LoggerConfiguration()
		.MinimumLevel
		.Verbose()
		.Enrich
		.FromLogContext()
		.WriteTo
		.RollingFile(appSettings.LogDirectory + @"\ids-{Date}.txt");

	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();

		// Writes log statements to the console when in develop environment
		serilog.WriteTo.LiterateConsole(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message}{NewLine}{Exception}{NewLine}");
	}

	// Logging configuration
	loggerFactory
		.WithFilter(new FilterLoggerSettings
						{
							{ "IdentityServer", LogLevel.Trace },
							{ "Microsoft", LogLevel.Trace },
							{ "System", LogLevel.Trace },
						})
		.AddSerilog(serilog.CreateLogger());

	// Seeding the database with the initial clients and users
	IdentitySeed.SeedDatabase(app, Configuration);

	// Specifies that we are using Identity and the IdentityServer
	app.UseIdentity();
	app.UseIdentityServer();
	
	app.UseStaticFiles();
	app.UseMvcWithDefaultRoute();            
}
```

**Comment by brockallen** [comment]
Yea, not sure. I'd enable ASP.NET Core logging to see what it says.

**Comment by rezareAW** [comment]
Ok thank you for your time on this.  I think I may have found the solution (unless you tell me otherwise).  

The problem seems to be I am using the IdentityServer4 extension method for signin rather than SignInManger (which in turn uses ClaimsFactory).

...
`await HttpContext.Authentication.SignInAsync(identityUser.Id, identityUser.UserName, props, securityClaim);`
...

it references in AuthenticationManagerExtensions that lives in IdentityServer4. which in turn calls one of the overloads such as 

```
public static async Task SignInAsync(this AuthenticationManager manager, string subject, string name, params Claim[] claims)
{
	var scheme = manager.GetIdentityServerAuthenticationScheme();

	var principal = IdentityServerPrincipal.Create(subject, name, claims);
	await manager.SignInAsync(scheme, principal);
}

in the ServerPrincipal.Create method there is nothing in there about adding the security claim

public static ClaimsPrincipal Create(
            string subject,
            string name,
            string identityProvider,
            IEnumerable<string> authenticationMethods,
            params Claim[] claims)
{
	if (subject.IsMissing()) throw new ArgumentNullException(nameof(subject));
	if (name.IsMissing()) throw new ArgumentNullException(nameof(name));
	if (authenticationMethods.IsNullOrEmpty()) throw new ArgumentNullException(nameof(authenticationMethods));
	if (identityProvider.IsMissing()) throw new ArgumentNullException(nameof(identityProvider));
	
	var allClaims = new List<Claim>
	{
		new Claim(JwtClaimTypes.Subject, subject),
		new Claim(JwtClaimTypes.Name, name),
		new Claim(JwtClaimTypes.IdentityProvider, identityProvider),
		new Claim(JwtClaimTypes.AuthenticationTime, IdentityServerDateTime.UtcNow.ToEpochTime().ToString(), ClaimValueTypes.Integer)
	};

	foreach (var amr in authenticationMethods)
	{
		allClaims.Add(new Claim(JwtClaimTypes.AuthenticationMethod, amr));
	}

	foreach (var claim in claims)
	{
		allClaims.Add(claim);
	}

	var id = new ClaimsIdentity(allClaims.Distinct(new ClaimComparer()), Constants.IdentityServerAuthenticationType, JwtClaimTypes.Name, JwtClaimTypes.Role);
    return new ClaimsPrincipal(id);
}
```

I'm wondering if I should be injecting an instance of SignInManager to my AccountController and using that instead?

`await _signInManager.SignInAsync(identityUser, props);`

**Comment by brockallen** [comment]
> The problem seems to be I am using the IdentityServer4 extension method for signin rather than SignInManger (which in turn uses ClaimsFactory).

So yes, that explains it. If you're using ASP.NET Identity you have to use their APIs via their framework to validate credentials and issue the cookie.
