### ISSUE TITLE
"idp claim is missing" with AspNetIdentity 2.0.0-rc1

### ISSUE THREAD

**Issue by antonioromano** [IdentityServer/IdentityServer4.AspNetIdentity#40]
Sometimes the identityserver throw the error:
```Unhandled exception: System.InvalidOperationException: idp claim is missing```
or
```IdentityServer4 message: idp claim is missing stack: at IdentityServer4.Extensions.PrincipalExtensions.GetIdentityProvider(IIdentity identity)``

I can't provide any steps to reproduce it. It seems that the server tries to load some data from the cache getting an error, and what happens is an error response to the user who is trying to log in.

Any idea on what I can do to fix it? Is this issue under control?

**Comment by brockallen** [comment]
So somehow you're losing the idp claim in your cookie. You need to research that. We document that it's required: http://docs.identityserver.io/en/release/topics/signin.html#authenticationmanager-and-claims

**Comment by brockallen** [comment]
My only guess is that maybe you're not using the `SignInManager` to issue your cookies, and instead you're only using the `HttpContext` APIs?

**Comment by brockallen** [comment]
Any update? Can we close?

**Comment by roblapp** [comment]
I am still getting this error in 2.0.0... Why was the issue closed? How can I avoid this error?

**Comment by brockallen** [comment]
> How can I avoid this error?

Can you first establish the cause? OP was not able to, thus it was closed.
