### ISSUE TITLE
Registration of UserClaimsFactory is incorrect when a custom UserClaimsPrincipalFactory has already been registered

### ISSUE THREAD

**Issue by justin-mellor** [IdentityServer/IdentityServer4.AspNetIdentity#41]
Introducted by the changes in 2.0.0-rc1-update1

If you register a custom UserClaimsPrincipalFactory with AspNetIdentity
```
services.AddIdentity<TUser>()
    .AddClaimsPrincipalFactory<MyClaimsPrincipalFactory>()
```

then when you add IdentityServer registration
```
services..AddIdentityServer()
    .AddAspNetIdentity<TUser>()
```

the registered ClaimsPrincipalFactory is reset back to the default AspNetIdentity one.

This is because the Decorator code is looking for the first DI registration, not the last.

**Comment by brockallen** [comment]
Good catch. Perhaps we should remove all registrations?

**Comment by brockallen** [comment]
I pushed 2.0.0-rc1-update2  -- can you test it for me, please?

**Comment by justin-mellor** [comment]
All fixed. Cheers.

**Comment by brockallen** [comment]
great thanks!
