### ISSUE TITLE
Make UserClaimsFactory public

### ISSUE THREAD

**Issue by hikalkan** [IdentityServer/IdentityServer4.AspNetIdentity#43]
Please make UserClaimsFactory public again. Because we are inheriting from it to add custom claims in the Create method (see https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp.ZeroCore.IdentityServer4/IdentityServer4/AbpIdentityServerUserClaimsPrincipalFactory.cs#L15).

**Comment by brockallen** [comment]
I changed it to use a decorator pattern, so you just need to inject yours into DI and we will wrap it. Did you try that?

**Comment by hikalkan** [comment]
That means if I register my implementation before, IdentityServer's UserClaimsFactory will decorate my implementation. Thanks a lot.

**Comment by brockallen** [comment]
Yep.
