### ISSUE TITLE
How to auto-provision users in ASP.Net Core 2.0 app

### ISSUE THREAD

**Issue by ElanHasson** [IdentityServer/IdentityServer4.AspNetIdentity#45]
I am using IdentityServer4 in a separate web application and using a different ASP.Net Core 2.0 MVC app to via services.AddAuthentication...AddOpenIdConnect().

I can successfully login via the IdSvr4 instance, but I get stuck in a redirect loop after successfuly login. 

It takes me into a redirect loop for:
![image](https://user-images.githubusercontent.com/234704/31312968-a3d16dc8-aba1-11e7-9a19-a6b770380303.png)

Based on my understanding, after successful Oidc login, I need to auto provision an account in the MVC app's Identity Store (UserManager, etc) . Similar to the ExternalLoginCallback functionality. 

How do I achieve the same type of behavior?

Thanks.

**Comment by ElanHasson** [comment]
I think the solution has to do with CookieAuthenticationEvents().

**Comment by brockallen** [comment]
Yes, something like this would up to the client app if they wanted to record the user in its own DB.
