### ISSUE TITLE
AutomaticRedirectAfterSignOut doesn't work

### ISSUE THREAD

**Issue by jgbright** [IdentityServer/IdentityServer4.AspNetIdentity#46]
The automatic redirect after sign out feature doesn't work.  It doesn't redirect the user, because the JavaScript file that does the redirect is missing.  I think it just needs a copy of the file from the IdentityServer4 repo.

As an aside, why not just do a server side redirect?  Is there a benefit to doing it client side?

This feature is enabled with the following code.

`IdentityServer4.Quickstart.UI.AutomaticRedirectAfterSignOut = false;`, 

The redirect is intended to occur in `src\Host\Views\Account\LoggedOut.cshtml` by running this code.

```
@if (Model.AutomaticRedirectAfterSignOut)
{
    <script src="~/js/signout-redirect.js"></script>
}
```

That JavaScript file doesn't exist, so an error appears in the browser console and the redirect does not occur.

**Comment by brockallen** [comment]
Feel free to send a PR that adds it.

**Comment by brockallen** [comment]
Ah, looks like you already did. I'll have a look. Thanks.

**Comment by brockallen** [comment]
Merged, thanks.
