### ISSUE TITLE
IResourceOwnerPasswordValidator not using SignInManager<ApplicationUser>.CreateUserPrincipalAsync

### ISSUE THREAD

**Issue by mrbucurie** [IdentityServer/IdentityServer4.AspNetIdentity#49]
When using the ResourceOwnerPassword grant, the `ResourceOwnerPasswordValidator` does not use the `UserClaimsPrincipalFactory<ApplicationUser>.CreateAsync` method to fill in the claims; as it is being done for the Implicit grant.

I would expect the AspNetIdentity is also integrated with the ResourceOwnerPassword.

What about adding the following change to the `ResourceOwnerPasswordValidator` ?

```
public virtual async Task ValidateAsync(ResourceOwnerPasswordValidationContext context)
{
  var user = await _userManager.FindByNameAsync(context.UserName);
  if (user != null)
  {
    var result = await _signInManager.CheckPasswordSignInAsync(user, context.Password, true);
    if (result.Succeeded)
    {
      var sub = await _userManager.GetUserIdAsync(user);
      
      var claimsIdentity = await _signInManager.CreateUserPrincipalAsync(user);
      
      _logger.LogInformation("Credentials validated for username: {username}", context.UserName);
      await _events.RaiseAsync(new UserLoginSuccessEvent(context.UserName, sub, context.UserName, interactive: false));
      
      context.Result = new GrantValidationResult(sub, OidcConstants.AuthenticationMethods.Password, claimsIdentity.Claims);
      return;
    }
...
```

**Comment by brockallen** [comment]
The main result of `IResourceOwnerPasswordValidator` is a subject claim. The other claims would normally be loaded in the profile service. Is there something I'm missing in what you need or are trying to do?

**Comment by brockallen** [comment]
All set on this issue -- can we close?
