### ISSUE TITLE
Implicit Flow Question

### ISSUE THREAD

**Issue by Singularity222** [IdentityServer/IdentityServer4.AspNetIdentity#52]
I have an application that uses a custom version of the ResourceOwnerPasswordValidator class using the Resource Owner Password grant type. It's a .Net Core Web API application with Identity Server 4 built in. Currently, the user sends their username and password via an Angular application, the ResourceOwnerPasswordValidator class verifies their login credentials and a token is returned. We are thinking of switching from the Resource Owner Password grant type to the Implicit grant type. Would the ResourceOwnerPasswordValidator class still be used to validate the user's credentials when using the Implicit grant type?

**Comment by brockallen** [comment]
No. You'd validate the credentials in the login page that you build that's hosted at IdentityServer. See our quickstarts for more info.

**Comment by Singularity222** [comment]
Ok, thanks for the insight. A follow-up question I have if it's not too much trouble. Currently the application that we have set up uses the Resource Owner Password grant type with ASP.NET Core Identity as the user data store. There's talk of adding Google authentication as well. Would we still be able to keep the current resource owner password grant type and be able to integrate Google authentication as well? Currently, we request a token and store it within the browser. Any authenticated request has the token sent along to the API. Is it feasible to think after authenticating via Google we could still follow the same flow of authentication -> token returned -> pass to API? I'm curious how much the addition of Google authentication is going to affect what we have set up already. Also, I think we'd have to associate the Google account provider to the ASP.Net Core Identity local user. All of this would be done via an Angular application. Do you know of any resources that might help navigate us in the right direction? I know this is probably quite a specific usage scenario. Thanks for the help.

**Comment by brockallen** [comment]
If you want federation you can't use resource owner flow.

**Comment by brockallen** [comment]
Odd... are you sure you don't have some odd version mismatch?

**Comment by Singularity222** [comment]
Ok, so if I have an application that currently uses the resource owner grant to authenticate users that are first party, is there anyway to enable google authentication in my app while still using the resource owner password grant?

**Comment by brockallen** [comment]
Didn't you see what I wrote above?

**Comment by brockallen** [comment]
All set on this issue -- can we close?
