### ISSUE TITLE
How to set Identity options in AddAspNetIdentity?

### ISSUE THREAD

**Issue by freerider7777** [IdentityServer/IdentityServer4.AspNetIdentity#53]
How to change Lockout parameters if I want to change the defaults?

```
        public static IIdentityServerBuilder AddAspNetIdentity<TUser>(this IIdentityServerBuilder builder)
            where TUser : class
        {
//
            builder.Services.Configure<IdentityOptions>(options =>
            {
// how to set this:
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromHours(1);
                options.Lockout.MaxFailedAccessAttempts = 3;
//
```

**Comment by brockallen** [comment]
You don't. You'd do it normally when you add ASP.NET Identity.

**Comment by freerider7777** [comment]
If I add this code in ConfigureServices (after AddIdentityServer)
           services.AddIdentity<ApplicationUser, IdentityRole>(o =>
           {
               //other stuff
               o.Tokens.ChangePhoneNumberTokenProvider = "Phone";
           });

on Configure -> app.UseIdentityServer() gives an exception
System.InvalidOperationException: 'Scheme already exists: Identity.Application'

**Comment by brockallen** [comment]
Can you try to repo this in our quickstart? That way if there's a bug I can also repo it to find out the problem. 

https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/6_AspNetIdentity

**Comment by freerider7777** [comment]
Right in this sample, try adding this at line 50 IdentityServerWithAspNetIdentity -> Startup.cs:
```
            services.AddIdentity<ApplicationUser, IdentityRole>(o =>
            {
                //other stuff
                o.Tokens.ChangePhoneNumberTokenProvider = "Phone";
            });
```

**Comment by brockallen** [comment]
Ok, I'll have a look.

**Comment by brockallen** [comment]
I added the same code you have above and it's working fine. Perhaps you have some other call elsewhere to `AddIdentity`.

**Comment by freerider7777** [comment]
Strange... I took complete clean repository (IdentityServer4.Samples), VS 2017 15.4.3 adding these lines (just these) gives an exception in Configure -> app.UseIdentityServer();
screenshot:
https://1drv.ms/i/s!AubEQRUBsL6GiYoHIRl4rfuT50HbIA

**Comment by brockallen** [comment]
Sorry, I don't know... please debug some more and let us know what you discover.

**Comment by brockallen** [comment]
Any update?

**Comment by freerider7777** [comment]
No changes :( Can share (archived maybe) your project with added lines? Seems services.AddIdentity and services.AddIdentityServer are adding smth twice...

**Comment by brockallen** [comment]
I updated the QS 6 showing options, and it's working.

I was able to repro your issue by calling:

```
services.AddIdentity<ApplicationUser, IdentityRole>()
```

twice in `ConfigureServices`, so perhaps that's your issue?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by freerider7777** [comment]
Yes, you are right! It was called twice - I didn't notice...
Thanks for support.
