### ISSUE TITLE
unnecessary database roundtrips

### ISSUE THREAD

**Issue by alecrt** [IdentityServer/IdentityServer4.AspNetIdentity#55]
I was looking at ProfileService and i'm asking myself why you use the IUserClaimsPrincipalFactory to create a new ClaimsPrincipal when you have the very same one available as context.Subject.

https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/ec46ee96d3ece17e7113accde4f624c790b0663e/src/IdentityServer4.AspNetIdentity/ProfileService.cs#L42-L45

Thank you!

**Comment by brockallen** [comment]
That's the dedicated API in ASP.NET Identity for creating the claims for a user. Our profile service was designed to leverage the existing API in ASP.NET Identity.

**Comment by alecrt** [comment]
That's clear.
But what's wrong doing something like that without fetching the user and re-creating the claimsPrincipal? 
`context.AddRequestedClaims(context.Subject.Claims);`

context.Subject should already be created using the very same IUserClaimsPrincipalFactory you're injecting in the constructor. Or am I wrong?

Thanks,

**Comment by brockallen** [comment]
> context.Subject should already be created using the very same IUserClaimsPrincipalFactory you're injecting in the constructor. Or am I wrong?

Subject could have anything and it's not always the subject from the login UI

**Comment by alecrt** [comment]
Perfect. Fine, can be closed!

Thank you!

Inviato da iPhone

Il giorno 07 dic 2017, alle ore 18:08, Brock Allen <notifications@github.com<mailto:notifications@github.com>> ha scritto:


context.Subject should already be created using the very same IUserClaimsPrincipalFactory you're injecting in the constructor. Or am I wrong?

Subject could have anything and it's not always the subject from the login UI
