### ISSUE TITLE
How to break into token requests?

### ISSUE THREAD

**Issue by hoagsie** [IdentityServer/IdentityServer4.AspNetIdentity#56]
I need to get visibility into the token request so that I can append an additional header on the response. I've tried creating normal middleware for this without success. Further, I've attempted to attach to `JwtBearerEvents`.`OnMessageReceived`, `OnTokenValidated`,  and `OnChallenge` as well as defining custom classes for `AddCustomTokenRequestValidator<>` and `AddAuthorizeInteractionResponseGenerator<>`. All of these attempts have failed.

How do I go about this? Moreover, I'm trying to find if or how I could remap the token endpoint to a custom controller route. Is this possible?

**Comment by leastprivilege** [comment]
Did you try to add a header to the HttpResponse in a custom validator? You probably need to subscribe to a event on the response for that?

**Comment by hoagsie** [comment]
Getting that response is proving to be the challenge. None of the methods I
mentioned let me access it nor did my custom middleware get a chance to see
it before a token was issued.

Is there a prescribed method of getting the response to a connect/token
request or rerouting that request to a controller method?

**Comment by brockallen** [comment]
I think this issue is unrelated to ASP.NET Identity. Feel free to open a new issue on the main repo: https://github.com/IdentityServer/IdentityServer4/issues
