### ISSUE TITLE
Docs: Quickstart uses UI not mentioned in tutorial

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4.AspNetIdentity#7]
If you follow the Quickstart docs for ASP.NET Identity, no UI is configured for IdentityServer.

It's mentioned at the end that you can use the Quickstart UI for consent screens, but during the tutorial login views and services are used that are not mentioned in the doc.

**Comment by brockallen** [comment]
Well, no UI is mentioned throughout all of the quickstarts. All that's done is that the quickstart UI is added, and in this particular quickstart, it's just copied over (admittedly for you in the sample code). 

In short, we don't have a quickstart on building a UI, as that's less a quickstart and more of a full blown tutorial. It's certainly something that needs to be added.

**Comment by scottbrady91** [comment]
Going from start to finish we add the Quickstart UI in 'Adding User Authentication with OpenID Connect' when still using In-Memory users. Then when we hit 'Using ASP.NET Core Identity' we create a new project using the VS templates and then add in Identity Server as we go.

Just ran through that though and realized we are using the UI from the VS template though... That's clever, my bad.
