### ISSUE TITLE
Are IdSvr scopes/claims not available when using AspNetIdentity?

### ISSUE THREAD

**Issue by aluethi** [IdentityServer/IdentityServer4.AspNetIdentity#8]
Hi there,
First of all: Thanks for all the good work with the IdSvr project -- I love to work with it.

The problem I have is, that with IdSvr4, the EF and AspNet ID extensions, I was not able to get the IdSvr scopes/claims from the EF database. The only claims I got were the ones from the AspNet ID part of the DB.
While digging a bit through the code I was wondering why the IdSvr scopes/claims are not added somwhere here:
https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/ProfileService.cs#L32

My question now: Is that by design, that only the AspNet ID claims are exposed? (if so whats the reasoning behind?) or is this just a feature that is still missing and will be implemented in a future release? (with other words, do I need to re-implement the ProfileService to get the IdSvr scopes/claims for now?)

Thanks you for your help!
Best,
Andi

**Comment by leastprivilege** [comment]
scopes are part of the protocol. we take care of that.
